### PR TITLE
US-977: Replace absalomedia/sassphp with scssphp/scssphp

### PR DESCRIPTION
**Pull request by stefanospetrakis**

### CODE REVIEW

**Comment by stefanospetrakis** [comment]
Hey there good people! This PR even has some green tests on its side; I mean Vis.Reg.Aut.Tests ;)
see https://github.com/iqual-ch/alteag-sw-project/runs/7307161551?check_suite_focus=true
as well as https://github.com/iqual-ch/alteag-sw-project/pull/6#issuecomment-1177730385

**Comment by pvbergen** [comment]
Looks good to me, nice work with the tests! I can't find the artifact/report of the tests in the other PRs. Where do I need to look? :)

**Review by pvbergen — APPROVED** [review]

**Comment by stefanospetrakis** [comment]
Hey @pvbergen ; thanks! The artifact was not being uploaded in some cases (fixed that) for failing tests. And there is no report, apart from the clean/green state for successful runs.

How do you work with PRs again? I got one approval, am I free to merge?

**Comment by pvbergen** [comment]
I was a bit quick with my approval... Can we do this as version 3.x instead of changing 2.x? We still can backport later but I would like to keep the current state available.

Thanks for the explanation about the report.

**Review by pvbergen — DISMISSED** [review]
Provide as 3.x instead 2.x

**Review by pvbergen — APPROVED** [review]
Thanks ;)

**Comment by pvbergen** [comment]
RTBC

**Comment by stefanospetrakis** [comment]
Running tests in that sandbox PR again (since I changed stuff, right?) after pretty-printing JSON
https://github.com/iqual-ch/alteag-sw-project/runs/7317620257?check_suite_focus=true

**Comment by stefanospetrakis** [comment]
Tests came out clean (https://github.com/iqual-ch/alteag-sw-project/actions/runs/2662506554) after forcing a theme build in the github action

**Comment by pvbergen** [comment]
This is fine to be released for me :)

**Review by martinstadelmann — APPROVED** [review]
Also looks good to me. Comparing the performance between `2.x` and `3.x` would also be interesting.

**Comment by stefanospetrakis** [comment]
> Also looks good to me. Comparing the performance between `2.x` and `3.x` would also be interesting.

hey @martinstadelmann , it's 2-3 times slower with a simple `time`. Gonna merge this now into the 3.x branch.

image

**Comment by martinstadelmann** [comment]
FYI: The compiler handles a few things slightly different. Namely it doesn't shorten colors, uses whitespaces in some places but leaves them out in others and uses doublequotes for some properties. Nothing to worry about.

image
image
image

I switched to the new compiler on the [`3.x` branch of `iq_barrio`](https://github.com/iqual-ch/iq_barrio/tree/3.x).

**Comment by martinstadelmann** [comment]
Another update and note: it is also a bit more picky when it comes to file names apparently. The old version seems to have ignored the unfortunate file naming while the new version errors out, rightly so...

image

(Example form the [iqualch-sw-project](https://github.com/iqual-ch/iqualch-sw-project/tree/main/app/public/themes/custom/iq_custom/resources/sass))

**Pull request merged**
